### ISSUE TITLE
[Megatron Base Version] Would mind share the based version of Megatron ?

### ISSUE THREAD

**Issue by dumpmemory** [epfLLM/Megatron-LLM#67]
I have found the code for get_checkpoint_name(s) and DistributedOptimizer are different. The upstream version had fix many bugs . Would u mind rebase it ?

**Comment by martinjaggi** [comment]
the base version of [NVIDIA/Megatron-LM](https://github.com/NVIDIA/Megatron-LM) which our code branched of is March 28, 2023.

since then the structure of the base repo code has been refactored a bit by the NVIDIA team also. in terms of functionality though not much was changed. or could you point to a concrete bug which is present in our code and not in their updated one, which impacts the use?

so far we haven't encountered bugs in our training with Llama2 models of all sizes.

of course it would be best to rebase the code on top of newest megatron-lm, but this would take quite some effort. if anyone would like to help preparing the code that would be more than welcome

**Comment by kylematoba** [comment]
Hi, sorry, we seem to have lost the actual commit, but we're pretty sure it's `035cae2ef9cc770784a3c3f2f46ecf9cd0d1380c`, based on the timing.

**Comment by 13416157913** [comment]
> e seem to have lost the actual com

I meet the same issue,when I use --use_distributed_optimizer it error data parallel group is not initialized. How to solve it?
