### ISSUE TITLE
[Save checkpoint needs long time]

### ISSUE THREAD

**Issue by mynewstart** [epfLLM/Megatron-LLM#69]
Hi,
I am using your code to train llama 13b model, but I noticed that the time it takes to save a checkpoint is quite long. It took 5 minutes for the first save steps, and 15 minutes for the second save. Therefore, I have currently set torch.distributed.init_process_group(timeout=timedelta(minutes=120)). What could be the reason for this?

**Comment by kylematoba** [comment]
I'll close this because I don't really see an issue here: saving large files unavoidably takes time -- it takes us about 10 minutes plus or minus a bit to write a 70b checkpoint, and how much time it should takes depends on many things to accurately assess. 

What you see is in the same ballpark as what we see. I'd ask that you come with a more precise characterization of a potential problem in our code if you want further investigation.
